### PR TITLE
[WIP] Survey form

### PR DESCRIPTION
**Pull request by wilsonehusin**
Currently working on front-end for survey form.

### CODE REVIEW

**Comment by wilsonehusin** [comment]
Plan:
- Customers are filling in 3 categories of survey: Price, Quality, Would Revisit.  
  - Price and Quality are both 1-5 rating system  
  - Would Revisit is Yes, No, Maybe input
- Surveys are reachable by going to `/survey/<hashcode>`
  - `app.py` should check if hashcode is valid (i.e. associated with an account)
    - Render page if exist, otherwise error code

Thoughts on database? @EDawg878 @era878 @Jayxuchen

**Comment by EDawg878** [comment]
I think the database could look something like this:
1) Create a table `survey` with fields for account id, rating, price, quality, revisit and a primary key of restaurant id
2) Create a table `survey_hash` with a primary key being the generated hash key and fields for the account_id, restaurant_id

**Comment by wilsonehusin** [comment]
Is it possible that we relate the `survey_hash` with order summary? I was thinking maybe we could show the price the customer paid and when was this visit (just to make it clear to them).

screenshot 2017-10-28 at 12 07 45

**Comment by wilsonehusin** [comment]
@Jayxuchen can you check if your stuff is merged properly to this branch? especially `test_data.sql`

If everything works we can merge this to master @EDawg878 @Jayxuchen

**Pull request merged**
